<a href="https://colab.research.google.com/github/bunyadahmadli/TryCNN/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install pandas
!pip install numpy as np
!pip install keras
!pip install opencv-python


In [29]:
import cv2
import numpy as np
from keras.models import Sequential
from keras.layers import  Dense,Activation,Conv2D,Dropout,Flatten
from keras.layers.convolutional import Convolution2D,MaxPooling2D
from keras.optimizers import *
from keras import optimizers
from keras.layers.normalization import BatchNormalization


In [21]:
import os
os.chdir('kalemler')
!ls

10.jpg	12.jpg	14.jpg	16.jpg	18.jpg	1..jpg	2.jpg  4.jpg  6.jpg  9.jpg
11.jpg	13.jpg	15.jpg	17.jpg	19.jpg	20.jpg	3.jpg  5.jpg  7.jpg


In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [26]:
#read data
inputdata = np.array([])

for i in range (19):
  inputimg = 0
  i=i+1
  filepath = '%s.jpg'%i
  inputimg = cv2.imread('%s'%filepath)
  print(inputimg)
  try:
    resizeimg = cv2.resize(inputimg,(224,224))
    inputdata = np.append(inputdata,resizeimg)
  except:
    continue
inputdata = np.reshape(inputdata,(-1,224,224,3))
np.save("inputdata",inputdata)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

In [32]:
inputdata = np.load('inputdata.npy')

outputdata = np.array([[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]])

splitinput  = inputdata[1:4]
splitinput = np.append(splitinput,inputdata[17:20])

splitoutput = np.array([[1.0],[1,0],[1,0],[0,1],[0,1],[0,1]])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [37]:
model = Sequential()

model.add(Conv2D(96,11,strides=(4,4),input_shape=(224,224,3)))
model.add(MaxPooling2D(5,5))
model.add(Conv2D(256,5))
model.add(Conv2D(384,3))
model.add(Conv2D(384,3))
model.add(Conv2D(256,2))
,
model.add(Flatten())

model.add(Dense(4096,activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(4096,activation='relu'))
model.add(Dense(2))

model.add(Activation('softmax'))

model.compile(loss = 'binary_crossentropy',optimizer=optimizers.RMSprop(lr=0.00001),metrics= ['accurancy'])
model.summary()

model.fit(inputdata,outputdata,batch_size=2,epochs=1,validation_data = (splitinput,splitoutput))


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_15 (Conv2D)           (None, 54, 54, 96)        34944     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 10, 10, 96)        0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 6, 6, 256)         614656    
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 4, 4, 384)         885120    
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 2, 2, 384)         1327488   
_________________________________________________________________
conv2d_19 (Conv2D)           (None, 1, 1, 256)         393472    
_________________________________________________________________
flatten_2 (Flatten)          (None, 256)              

ValueError: ignored